"""
CAAS BMAD Deployment Preparer

배포 아티팩트 생성을 수행합니다.
requirements.txt, Dockerfile, docker-compose.yml 등을 생성합니다.
"""

import logging
from typing import Any, Dict, List

logger = logging.getLogger("caas_framework.bmad.deployer")


class DeploymentArtifacts:
    """배포 아티팩트"""

    def __init__(self):
        self.files: Dict[str, str] = {}

    def add_file(self, filename: str, content: str):
        """파일 추가"""
        self.files[filename] = content

    def to_dict(self) -> Dict[str, Any]:
        """딕셔너리로 변환"""
        return {
            "files": list(self.files.keys()),
            "total_files": len(self.files),
        }


class DeploymentPreparer:
    """
    배포 준비기

    배포에 필요한 모든 아티팩트를 생성합니다.
    """

    def __init__(self):
        self.logger = logger
        # 기본 Python 의존성
        self.base_dependencies = [
            "crewai>=0.65.0",
            "python-dotenv>=1.0.0",
            "pydantic>=2.0.0",
        ]

    def prepare_deployment(
        self,
        project_name: str,
        code_files: Dict[str, str],
        agent_specs: List[Dict[str, Any]],
    ) -> DeploymentArtifacts:
        """
        배포 준비

        Args:
            project_name: 프로젝트 이름
            code_files: 코드 파일
            agent_specs: 에이전트 스펙

        Returns:
            DeploymentArtifacts: 배포 아티팩트
        """
        artifacts = DeploymentArtifacts()

        # 1. requirements.txt 생성
        artifacts.add_file(
            "requirements.txt",
            self._generate_requirements(agent_specs),
        )

        # 2. Dockerfile 생성
        artifacts.add_file(
            "Dockerfile",
            self._generate_dockerfile(project_name),
        )

        # 3. docker-compose.yml 생성
        artifacts.add_file(
            "docker-compose.yml",
            self._generate_docker_compose(project_name),
        )

        # 4. .dockerignore 생성
        artifacts.add_file(
            ".dockerignore",
            self._generate_dockerignore(),
        )

        # 5. .env.example 생성
        artifacts.add_file(
            ".env.example",
            self._generate_env_example(agent_specs),
        )

        # 6. README_DEPLOYMENT.md 생성
        artifacts.add_file(
            "README_DEPLOYMENT.md",
            self._generate_deployment_readme(project_name),
        )

        self.logger.info(f"배포 아티팩트 {len(artifacts.files)}개 생성 완료")
        return artifacts

    def _generate_requirements(self, agent_specs: List[Dict[str, Any]]) -> str:
        """requirements.txt 생성"""
        dependencies = self.base_dependencies.copy()

        # 에이전트가 사용하는 도구에 따라 의존성 추가
        tools_used = set()
        for agent in agent_specs:
            tools_used.update(agent.get("tools", []))

        # 도구별 의존성 매핑
        tool_dependencies = {
            "web_search": ["duckduckgo-search>=5.0.0"],
            "scrape_website": ["beautifulsoup4>=4.12.0", "requests>=2.31.0"],
            "code_interpreter": ["jupyter>=1.0.0"],
        }

        for tool in tools_used:
            if tool in tool_dependencies:
                dependencies.extend(tool_dependencies[tool])

        # 중복 제거 및 정렬
        dependencies = sorted(set(dependencies))

        requirements = "# Generated by CAAS\n"
        requirements += "# Python dependencies for CrewAI project\n\n"
        requirements += "\n".join(dependencies)
        requirements += "\n"

        return requirements

    def _generate_dockerfile(self, project_name: str) -> str:
        """Dockerfile 생성"""
        return f"""# Generated by CAAS
# Dockerfile for {project_name}

FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Run the crew
CMD ["python", "main.py"]
"""

    def _generate_docker_compose(self, project_name: str) -> str:
        """docker-compose.yml 생성"""
        return f"""# Generated by CAAS
# Docker Compose configuration for {project_name}

version: '3.8'

services:
  {project_name}:
    build: .
    container_name: {project_name}
    environment:
      - OPENAI_API_KEY=${{OPENAI_API_KEY}}
      - ANTHROPIC_API_KEY=${{ANTHROPIC_API_KEY}}
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped

  # Optional: Add Neo4j for knowledge graph (if needed)
  # neo4j:
  #   image: neo4j:5
  #   container_name: {project_name}_neo4j
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     - NEO4J_AUTH=neo4j/password
  #   volumes:
  #     - neo4j_data:/data
  #
  # volumes:
  #   neo4j_data:
"""

    def _generate_dockerignore(self) -> str:
        """.dockerignore 생성"""
        return """# Generated by CAAS

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
*.egg-info/
dist/
build/

# Virtual environments
venv/
env/
ENV/

# IDE
.vscode/
.idea/
*.swp
*.swo

# Testing
.pytest_cache/
.coverage
htmlcov/

# Logs
*.log

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db

# Git
.git/
.gitignore
"""

    def _generate_env_example(self, agent_specs: List[Dict[str, Any]]) -> str:
        """.env.example 생성"""
        env_content = """# Generated by CAAS
# Environment variables template
# Copy this file to .env and fill in your values

# LLM Provider API Keys
OPENAI_API_KEY=your_openai_api_key_here
# ANTHROPIC_API_KEY=your_anthropic_api_key_here

# LLM Configuration
DEFAULT_LLM_PROVIDER=openai
DEFAULT_LLM_MODEL=gpt-4-turbo-preview

# Optional: Neo4j Configuration (if using knowledge graph)
# NEO4J_URI=bolt://localhost:7687
# NEO4J_USER=neo4j
# NEO4J_PASSWORD=password

# Project Configuration
LOG_LEVEL=INFO
OUTPUT_DIR=./output
"""

        return env_content

    def _generate_deployment_readme(self, project_name: str) -> str:
        """README_DEPLOYMENT.md 생성"""
        return f"""# Deployment Guide for {project_name}

Generated by CAAS (CrewAI Agent Auto-generation System)

## Prerequisites

- Python 3.11 or higher
- Docker and Docker Compose (optional, for containerized deployment)
- API keys for LLM providers (OpenAI, Anthropic, etc.)

## Local Deployment

### 1. Environment Setup

Copy the example environment file and configure it:

```bash
cp .env.example .env
```

Edit `.env` and add your API keys:

```bash
OPENAI_API_KEY=your_actual_api_key_here
```

### 2. Install Dependencies

Create a virtual environment and install dependencies:

```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
pip install -r requirements.txt
```

### 3. Run the Crew

```bash
python main.py
```

## Docker Deployment

### 1. Build the Docker Image

```bash
docker-compose build
```

### 2. Run with Docker Compose

```bash
# Make sure .env file exists with your API keys
docker-compose up
```

### 3. View Logs

```bash
docker-compose logs -f {project_name}
```

### 4. Stop the Container

```bash
docker-compose down
```

## Production Deployment

### Cloud Platforms

#### AWS

1. **EC2**: Deploy on an EC2 instance
   - Use the Dockerfile to build an image
   - Push to ECR (Elastic Container Registry)
   - Deploy to ECS or EKS

2. **Lambda**: For serverless deployment
   - Package the crew as a Lambda function
   - Use API Gateway for HTTP triggers

#### Google Cloud

1. **Cloud Run**: Serverless container deployment
   ```bash
   gcloud builds submit --tag gcr.io/PROJECT_ID/{project_name}
   gcloud run deploy --image gcr.io/PROJECT_ID/{project_name}
   ```

2. **GKE**: Kubernetes deployment
   - Use the provided Dockerfile
   - Deploy to Google Kubernetes Engine

#### Azure

1. **Container Instances**: Quick container deployment
2. **App Service**: PaaS deployment for Docker containers

### Environment Variables

Ensure all required environment variables are set in production:

- `OPENAI_API_KEY`: OpenAI API key (required)
- `DEFAULT_LLM_PROVIDER`: LLM provider (default: openai)
- `DEFAULT_LLM_MODEL`: Model name (default: gpt-4-turbo-preview)
- `LOG_LEVEL`: Logging level (default: INFO)

### Security Considerations

1. **Never commit `.env` files** - Keep API keys secure
2. **Use secrets management** - AWS Secrets Manager, GCP Secret Manager, etc.
3. **Limit API access** - Use API key restrictions
4. **Monitor usage** - Track API calls and costs
5. **Enable logging** - Monitor crew execution

## Monitoring

### Logs

- Local: Check `./logs/` directory
- Docker: Use `docker-compose logs`
- Production: Use cloud platform logging (CloudWatch, Stackdriver, etc.)

### Metrics

Monitor these key metrics:
- Crew execution success rate
- API call costs
- Execution duration
- Error rates

## Troubleshooting

### Common Issues

1. **API Key Errors**
   - Verify `.env` file exists and contains valid keys
   - Check API key permissions and quotas

2. **Import Errors**
   - Ensure all dependencies are installed: `pip install -r requirements.txt`
   - Check Python version: `python --version` (should be 3.11+)

3. **Docker Issues**
   - Verify Docker is running: `docker ps`
   - Rebuild image: `docker-compose build --no-cache`

4. **Performance Issues**
   - Increase timeout values
   - Use faster LLM models for development
   - Enable caching where applicable

## Support

For issues or questions:
- Check project documentation
- Review CrewAI documentation: https://docs.crewai.com
- Contact support: CAAS project maintainers

## License

Generated code is licensed under the same license as the CAAS project.
"""

    def generate_ci_cd(self, project_name: str) -> Dict[str, str]:
        """
        CI/CD 파이프라인 생성 (선택적)

        Args:
            project_name: 프로젝트 이름

        Returns:
            Dict[str, str]: CI/CD 파일
        """
        cicd_files = {}

        # GitHub Actions
        cicd_files[".github/workflows/ci.yml"] = self._generate_github_actions(project_name)

        # GitLab CI
        cicd_files[".gitlab-ci.yml"] = self._generate_gitlab_ci(project_name)

        return cicd_files

    def _generate_github_actions(self, project_name: str) -> str:
        """GitHub Actions 워크플로우 생성"""
        return f"""# Generated by CAAS
name: CI/CD for {project_name}

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        pytest tests/ -v --cov

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t {project_name}:latest .

    - name: Log in to registry
      run: echo "${{{{ secrets.DOCKER_PASSWORD }}}}" | docker login -u "${{{{ secrets.DOCKER_USERNAME }}}}" --password-stdin

    - name: Push image
      run: |
        docker tag {project_name}:latest ${{{{ secrets.DOCKER_USERNAME }}}}/{project_name}:latest
        docker push ${{{{ secrets.DOCKER_USERNAME }}}}/{project_name}:latest
"""

    def _generate_gitlab_ci(self, project_name: str) -> str:
        """GitLab CI 설정 생성"""
        return f"""# Generated by CAAS
stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest tests/ -v --cov

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t {project_name}:$CI_COMMIT_SHA .
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  script:
    - echo "Deploy to production"
    # Add your deployment commands here
  only:
    - main
  when: manual
"""
