"""
Traceability Matrix

Phase 2: Feature-to-Code Traceability
Tracks relationships between Features → Tasks → Code to ensure complete implementation.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set

from caas_framework.models.specifications import FeatureSpec, TaskSpecModel
from caas_framework.utils.logger import get_logger

logger = get_logger()


class ImplementationStatus(Enum):
    """Implementation status for features"""

    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    IMPLEMENTED = "implemented"
    VERIFIED = "verified"


@dataclass
class FeatureTrace:
    """
    Traceability information for a single feature

    Tracks:
    - Which tasks implement this feature
    - Which code files contain the implementation
    - Implementation status
    """

    feature_id: str
    feature_name: str

    # Task mappings
    implementing_tasks: List[str] = field(default_factory=list)  # Task IDs

    # Code mappings
    implementing_files: List[str] = field(default_factory=list)  # File paths
    implementing_functions: List[str] = field(default_factory=list)  # Function names

    # Status
    status: ImplementationStatus = ImplementationStatus.NOT_STARTED
    coverage_percentage: float = 0.0  # 0-100

    # Validation
    has_tests: bool = False
    test_files: List[str] = field(default_factory=list)

    # Metadata
    notes: str = ""


@dataclass
class TaskTrace:
    """
    Traceability information for a single task

    Tracks:
    - Which features this task implements
    - Which agent executes this task
    - Which code is generated by this task
    """

    task_id: str
    task_description: str
    agent_id: str

    # Feature mappings
    implements_features: List[str] = field(default_factory=list)  # Feature IDs

    # Code mappings
    generated_files: List[str] = field(default_factory=list)  # File paths
    modified_files: List[str] = field(default_factory=list)  # File paths

    # Status
    execution_status: str = "pending"  # pending, running, completed, failed


@dataclass
class CodeTrace:
    """
    Traceability information for code files

    Tracks:
    - Which features are implemented in this file
    - Which tasks generated/modified this file
    """

    file_path: str

    # Feature mappings
    implements_features: List[str] = field(default_factory=list)  # Feature IDs

    # Task mappings
    generated_by_task: Optional[str] = None  # Task ID
    modified_by_tasks: List[str] = field(default_factory=list)  # Task IDs

    # Analysis
    lines_of_code: int = 0
    has_tests: bool = False
    test_coverage: float = 0.0


class TraceabilityMatrix:
    """
    Complete traceability matrix for the project

    Maintains bidirectional mappings:
    - Feature → Task → Code (forward)
    - Code → Task → Feature (backward)

    Purpose:
    1. Ensure all features are implemented
    2. Track which code implements which feature
    3. Identify gaps in implementation
    4. Enable impact analysis for changes
    """

    def __init__(self):
        """Initialize empty traceability matrix"""
        self.logger = get_logger()

        # Core mappings
        self.features: Dict[str, FeatureTrace] = {}
        self.tasks: Dict[str, TaskTrace] = {}
        self.code_files: Dict[str, CodeTrace] = {}

        # Quick lookup indexes
        self._feature_to_tasks: Dict[str, Set[str]] = {}
        self._task_to_features: Dict[str, Set[str]] = {}
        self._feature_to_code: Dict[str, Set[str]] = {}
        self._code_to_features: Dict[str, Set[str]] = {}

    # ============================================================================
    # Feature Registration
    # ============================================================================

    def register_features(self, features: List[FeatureSpec]) -> None:
        """
        Register features to track

        Args:
            features: List of feature specifications
        """
        self.logger.info(f"Registering {len(features)} features for traceability")

        for feature in features:
            trace = FeatureTrace(
                feature_id=feature.id,
                feature_name=feature.name,
                status=ImplementationStatus.NOT_STARTED,
            )
            self.features[feature.id] = trace
            self._feature_to_tasks[feature.id] = set()
            self._feature_to_code[feature.id] = set()

        self.logger.info(f"✓ Registered {len(self.features)} features")

    # ============================================================================
    # Task Registration and Mapping
    # ============================================================================

    def register_task(self, task: TaskSpecModel, implements_features: List[str]) -> None:
        """
        Register a task and its feature mappings

        Args:
            task: Task specification
            implements_features: List of feature IDs this task implements
        """
        trace = TaskTrace(
            task_id=task.id,
            task_description=task.description,
            agent_id=getattr(task, "agent_id", "unknown"),
            implements_features=implements_features,
        )

        self.tasks[task.id] = trace
        self._task_to_features[task.id] = set(implements_features)

        # Update feature → task mappings
        for feature_id in implements_features:
            if feature_id in self.features:
                self.features[feature_id].implementing_tasks.append(task.id)
                self._feature_to_tasks.setdefault(feature_id, set()).add(task.id)

                # Update feature status
                if self.features[feature_id].status == ImplementationStatus.NOT_STARTED:
                    self.features[feature_id].status = ImplementationStatus.IN_PROGRESS
            else:
                self.logger.warning(f"Task {task.id} references unknown feature: {feature_id}")

        self.logger.debug(
            f"Registered task {task.id} implementing {len(implements_features)} features"
        )

    # ============================================================================
    # Code Registration and Mapping
    # ============================================================================

    def register_code(
        self, file_path: str, generated_by_task: str, implements_features: List[str]
    ) -> None:
        """
        Register generated code file

        Args:
            file_path: Path to code file
            generated_by_task: Task ID that generated this file
            implements_features: Feature IDs implemented in this file
        """
        trace = CodeTrace(
            file_path=file_path,
            generated_by_task=generated_by_task,
            implements_features=implements_features,
        )

        self.code_files[file_path] = trace
        self._code_to_features[file_path] = set(implements_features)

        # Update feature → code mappings
        for feature_id in implements_features:
            if feature_id in self.features:
                self.features[feature_id].implementing_files.append(file_path)
                self._feature_to_code.setdefault(feature_id, set()).add(file_path)

                # Update feature status
                self.features[feature_id].status = ImplementationStatus.IMPLEMENTED
            else:
                self.logger.warning(f"Code {file_path} references unknown feature: {feature_id}")

        # Update task → code mappings
        if generated_by_task in self.tasks:
            self.tasks[generated_by_task].generated_files.append(file_path)

        self.logger.debug(
            f"Registered code file {file_path} implementing {len(implements_features)} features"
        )

    # ============================================================================
    # Coverage Analysis
    # ============================================================================

    def analyze_coverage(self) -> Dict[str, Any]:
        """
        Analyze implementation coverage

        Returns:
            Coverage report with statistics and gaps
        """
        total_features = len(self.features)

        # Count features by status
        not_started = sum(
            1 for f in self.features.values() if f.status == ImplementationStatus.NOT_STARTED
        )
        in_progress = sum(
            1 for f in self.features.values() if f.status == ImplementationStatus.IN_PROGRESS
        )
        implemented = sum(
            1 for f in self.features.values() if f.status == ImplementationStatus.IMPLEMENTED
        )
        verified = sum(
            1 for f in self.features.values() if f.status == ImplementationStatus.VERIFIED
        )

        # Calculate percentages
        implementation_rate = (
            (implemented + verified) / total_features * 100 if total_features > 0 else 0
        )
        verification_rate = verified / total_features * 100 if total_features > 0 else 0

        # Find unimplemented features
        unimplemented_features = [
            {"id": f.feature_id, "name": f.feature_name, "status": f.status.value}
            for f in self.features.values()
            if f.status in (ImplementationStatus.NOT_STARTED, ImplementationStatus.IN_PROGRESS)
        ]

        report = {
            "summary": {
                "total_features": total_features,
                "total_tasks": len(self.tasks),
                "total_code_files": len(self.code_files),
                "implementation_rate": round(implementation_rate, 2),
                "verification_rate": round(verification_rate, 2),
            },
            "feature_status": {
                "not_started": not_started,
                "in_progress": in_progress,
                "implemented": implemented,
                "verified": verified,
            },
            "gaps": {
                "unimplemented_features": unimplemented_features,
                "features_without_tests": [
                    {"id": f.feature_id, "name": f.feature_name}
                    for f in self.features.values()
                    if not f.has_tests
                ],
            },
        }

        return report

    # ============================================================================
    # Query Methods
    # ============================================================================

    def get_feature_trace(self, feature_id: str) -> Optional[FeatureTrace]:
        """Get traceability info for a feature"""
        return self.features.get(feature_id)

    def get_tasks_for_feature(self, feature_id: str) -> List[TaskTrace]:
        """Get all tasks implementing a feature"""
        task_ids = self._feature_to_tasks.get(feature_id, set())
        return [self.tasks[tid] for tid in task_ids if tid in self.tasks]

    def get_code_for_feature(self, feature_id: str) -> List[CodeTrace]:
        """Get all code files implementing a feature"""
        file_paths = self._feature_to_code.get(feature_id, set())
        return [self.code_files[fp] for fp in file_paths if fp in self.code_files]

    def get_features_for_code(self, file_path: str) -> List[FeatureTrace]:
        """Get all features implemented in a code file"""
        feature_ids = self._code_to_features.get(file_path, set())
        return [self.features[fid] for fid in feature_ids if fid in self.features]

    def find_unimplemented_features(self) -> List[FeatureTrace]:
        """Find features that have not been implemented yet"""
        return [f for f in self.features.values() if f.status == ImplementationStatus.NOT_STARTED]

    # ============================================================================
    # Reporting
    # ============================================================================

    def generate_report(self) -> str:
        """
        Generate human-readable traceability report

        Returns:
            Formatted report string
        """
        coverage = self.analyze_coverage()

        report_lines = [
            "=" * 80,
            "TRACEABILITY REPORT",
            "=" * 80,
            "",
            "SUMMARY",
            "-" * 80,
            f"Total Features:      {coverage['summary']['total_features']}",
            f"Total Tasks:         {coverage['summary']['total_tasks']}",
            f"Total Code Files:    {coverage['summary']['total_code_files']}",
            f"Implementation Rate: {coverage['summary']['implementation_rate']:.1f}%",
            f"Verification Rate:   {coverage['summary']['verification_rate']:.1f}%",
            "",
            "FEATURE STATUS",
            "-" * 80,
            f"Not Started:  {coverage['feature_status']['not_started']}",
            f"In Progress:  {coverage['feature_status']['in_progress']}",
            f"Implemented:  {coverage['feature_status']['implemented']}",
            f"Verified:     {coverage['feature_status']['verified']}",
            "",
        ]

        # Unimplemented features
        if coverage["gaps"]["unimplemented_features"]:
            report_lines.extend(
                [
                    "UNIMPLEMENTED FEATURES",
                    "-" * 80,
                ]
            )
            for feature in coverage["gaps"]["unimplemented_features"]:
                report_lines.append(
                    f"  ✗ {feature['name']} ({feature['id']}) - {feature['status']}"
                )
            report_lines.append("")

        # Features without tests
        if coverage["gaps"]["features_without_tests"]:
            report_lines.extend(
                [
                    "FEATURES WITHOUT TESTS",
                    "-" * 80,
                ]
            )
            for feature in coverage["gaps"]["features_without_tests"][:10]:  # Limit to 10
                report_lines.append(f"  ⚠ {feature['name']} ({feature['id']})")
            if len(coverage["gaps"]["features_without_tests"]) > 10:
                report_lines.append(
                    f"  ... and {len(coverage['gaps']['features_without_tests']) - 10} more"
                )
            report_lines.append("")

        report_lines.append("=" * 80)

        return "\n".join(report_lines)

    def export_to_dict(self) -> Dict[str, Any]:
        """Export entire matrix to dictionary for serialization"""
        return {
            "features": {
                fid: {
                    "name": f.feature_name,
                    "status": f.status.value,
                    "implementing_tasks": f.implementing_tasks,
                    "implementing_files": f.implementing_files,
                    "coverage_percentage": f.coverage_percentage,
                }
                for fid, f in self.features.items()
            },
            "tasks": {
                tid: {
                    "description": t.task_description,
                    "agent_id": t.agent_id,
                    "implements_features": t.implements_features,
                    "generated_files": t.generated_files,
                }
                for tid, t in self.tasks.items()
            },
            "code_files": {
                path: {
                    "implements_features": c.implements_features,
                    "generated_by_task": c.generated_by_task,
                }
                for path, c in self.code_files.items()
            },
        }
